name: Trustifi CA Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC

permissions:
  contents: write
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      TRUSTIFI_UPDATED: "0"
    steps:
      - uses: actions/checkout@v4
      - name: Check for CA updates
        run: |
          python updater.py

      - name: Build package
        if: env.TRUSTIFI_UPDATED == '1'
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI
        if: env.TRUSTIFI_UPDATED == '1'
        uses: pypa/gh-action-pypi-publish@release/v1
